version: "3"

services:
  crypto-trading:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance_trader
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./user.cfg:/app/user.cfg
      - ./supported_coin_list:/app/supported_coin_list
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    command: ./start_bot.sh
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bangkok
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance_trader_api
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./user.cfg:/app/user.cfg
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - 5123:5123
    command: gunicorn binance_trade_bot.api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5123
    depends_on:
      - crypto-trading
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bangkok

  sqlitebrowser:
    image: ghcr.io/linuxserver/sqlitebrowser
    container_name: sqlitebrowser
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
    volumes:
      - ./data/config:/config
      - ./data:/data
    ports:
      - 3000:3000

  telegram-bot:
    build:
      context: .
      dockerfile: telegrambot/Dockerfile
    container_name: binance_trader_telegram_bot
    working_dir: /binance-trade-bot
    restart: unless-stopped
    volumes:
      - ./user.cfg:/binance-trade-bot/user.cfg
      - ./supported_coin_list:/binance-trade-bot/supported_coin_list
      - ./config:/binance-trade-bot/config
      - ./data:/binance-trade-bot/data
      - ./telegrambot/btb_manager_telegram:/binance-trade-bot/btb_manager_telegram
      - ./telegrambot/i18n:/binance-trade-bot/i18n
      - ./telegrambot/custom_scripts:/binance-trade-bot/custom_scripts
    command: python -m btb_manager_telegram -p ./
    # python -m btb_manager_telegram -p /binance-trade-bot
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bangkok