version: "3"

services:
  crypto-trading-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance_trader_2
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./user2.cfg:/app/user.cfg
      - ./supported_coin_list2:/app/supported_coin_list
      - ./data2:/app/data
      - ./logs2:/app/logs
      - ./config2:/app/config
    command: ./start_bot.sh
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bangkok
#  api-2:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: binance_trader_api_2
#    working_dir: /app
#    restart: unless-stopped
#    volumes:
#      - ./user2.cfg:/app/user.cfg
#      - ./data2:/app/data
#      - ./logs2:/app/logs
#    ports:
#      - 5125:5125
#    command: gunicorn binance_trade_bot.api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5125
#    depends_on:
#      - crypto-trading-2
#    environment:
#      - PYTHONUNBUFFERED=1
#      - TZ=Asia/Bangkok

#  sqlitebrowser-2:
#    image: ghcr.io/linuxserver/sqlitebrowser
#    container_name: sqlitebrowser_2
#    restart: unless-stopped
#    environment:
#      - PUID=1002
#      - PGID=1002
#      - TZ=Asia/Bangkok
#    volumes:
#      - ./data2/config:/config
#      - ./data2:/data
#    ports:
#      - 3002:3000

  telegram-bot-2:
    build:
      context: .
      dockerfile: telegrambot/Dockerfile
    container_name: binance_trader_telegram_bot_2
    working_dir: /binance-trade-bot
    restart: unless-stopped
    volumes:
      - ./user2.cfg:/binance-trade-bot/user.cfg
      - ./supported_coin_list2:/binance-trade-bot/supported_coin_list
      - ./config2:/binance-trade-bot/config
      - ./data2:/binance-trade-bot/data
      - ./telegrambot/btb_manager_telegram:/binance-trade-bot/btb_manager_telegram
      - ./telegrambot/i18n:/binance-trade-bot/i18n
      - ./telegrambot/custom_scripts:/binance-trade-bot/custom_scripts
    command: python -m btb_manager_telegram -p ./
    # python -m btb_manager_telegram -p /binance-trade-bot
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Bangkok